### ISSUE TITLE
do not alter `.libPath()` for downstream actions unless explicitly stated

### ISSUE THREAD

**Issue by maxheld83** [maxheld83/ghactions-install-deps#11]
*If* we set an `.Renviron` for all downstream actions by storing it in `github/workspace` that subtly changes the pkg search tree for all downstream R actions.

Maybe, it'd be better not to have the `.Reviron` persist, but let each action set it explicitly. Easier to reason about.

This problem arises (perhaps unlikely) with downstream actions which *wouldn't* need the dependencies of the package in question, such as a linting action (I *think* that doesn't need the pkg deps?).
If `.Renviron` is set persistently for all actions, that linting action faces an implicitly altered search tree. Might cause problems if, say, the pkg uses a dev version of a pkg C, but `lintr` needs the CRAN version of pkg C. 
(I think I've had these kinds of problems on Travis).
Broader concern -> https://github.com/r-lib/ghactions/issues/135

**Comment by jimhester** [comment]
> are R environment variables such as R_LIB_PATH just normal "shell" environment vars
yes, R _options_ are R specific, but the environment variables are just environment variables.

I would just do it in the dockerfile to start to keep things simple, unless you can't because creating the directory breaks things when the action is actually run

**Comment by maxheld83** [comment]
> I would just do it in the dockerfile to start to keep things simple, unless you can't because creating the directory breaks things when the action is actually run

Ok, I'm going to do test that in https://github.com/maxheld83/ghactions-install-deps/issues/14

**Comment by maxheld83** [comment]
ok, I think I just figured out what confused me so much the past couple of days: there appears to be a subtle bug in `act`, the FOSS local CLI runner of github actions -> https://github.com/nektos/act/issues/63

I've used `act` a lot to locally debug/get a sense of what's happening, but it seems to not reliably get the latest version of actions.

So I'm going to hard-code git commit SHAs for now.

Gotta use *something* local, waiting for github actions online takes too much time.

**Comment by maxheld83** [comment]
re: environment variables in docker:

- are R environment variables such as `R_LIB_PATH` just *normal* "shell" environment vars that I can declare with `export R_LIB_PATH="path/to/lib"`? I'm being dense, I thought R env vars where special and could only be declared from inside R. 
- I declared it with `RUN Rscript -e "Sys.setenv()"` etc.

I preliminarily decided *against* declaring `R_LIB_PATH` in the `Dockerfile`, because:

1) the `/github/home/` dir, into which I want to install, apparently only gets created at image *run time*, not *build time*. I was worried that `mkdir`ing it before might cause weird stuff at run time, when the github actions runner maps some *other* `/github/home/` etc into it.
2) I want this action (dependency installation) to be able to accept `R_LIB_PATH` as an optional argument or env var, so (at least for testing) it can also install elsewhere. If it's baked into the image, that's not possible, right?

I also wanted to make sure that remotes, and whatever else we might need for this action, *doesn't* get installed into `/github/home/lib...`, because I thought I'd be better *not* persist remotes, because it only serves this purpose.
I like the idea of altering the state of `/github/` as little as possible, so as to make it easy to reason about / debug individual actions (https://github.com/r-lib/ghactions/issues/135).

Anyway, I might be totally on the wrong track here / still pretty confused about some of these things, this is probably better discussed in person later today.
