### ISSUE TITLE
error out on nonavailable package

### ISSUE THREAD

**Issue by maxheld83** [maxheld83/ghactions-install-deps#19]
it turns out that the action currently exits with 0 (success) even when it can't find a package (say, because it does not exist).

The workflow should terminate when a package can't be found/installed.

**Comment by maxheld83** [comment]
I can think of a couple of ways around this:

1. elevate warnings to errors with `options(warn=2)` (note to self: here is [so](https://stackoverflow.com/questions/8217901/breaking-loop-when-warnings-appear-in-r))
2. wrap some `tryCatch()` around the remotes call to give them a different condition handler (raise `stop()`).
3. ~~use `remotes::local_pkg_deps()` to figure out after the fact what was actually installed~~ (that seems to cumbersome).

Which sounds best to you @jimhester?

**Comment by jimhester** [comment]
Do something like this https://github.com/travis-ci/travis-build/blob/22a3b1fbdb59170b6c302b2a6a28c8c9cb54b159/lib/travis/build/script/r.rb#L380-L384

But you could also just not worry about this problem for now.

**Comment by maxheld83** [comment]
done
